name: grafana
namespace: grafana
replicas: 1

image:
  repository: grafana/grafana
  tag: latest
  pullPolicy: Always

service:
  type: NodePort

ports:
  - 3000

env:

volumes:
  - name: grafana
    hostPath: "/mnt/core_data/k3s/grafana"
    mountPath: "/var/lib/grafana"

configMounts:
  - name: grafana-config
    configMap: grafana-config
    mountPath: /etc/grafana/grafana.ini
    subPath: grafana.ini
    readOnly: true

configMaps:
  grafana: ../grafana.ini

ingress:
  hosts:
    - domain: grafana.k3s.ravnet
      port: 3000
    - domain: grafana.ravcube.com
      port: 3000